# Generated by Django 5.0.7 on 2024-09-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('no_of_vaccancy', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
