# Generated by Django 5.0.7 on 2024-09-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picacodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='no_of_vaccancy',
            new_name='no_of_vaccancies',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='desc',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
    ]
