# Generated by Django 5.0.7 on 2024-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picacodapp', '0003_remove_jobs_experience_jobs_max_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('designation', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
